### ISSUE TITLE
Refactor openjdk-8-jre-headless to have "server"- and "client"-specific slices 

### ISSUE THREAD

**Issue by cjdcordeiro** [canonical/chisel-releases#152]
> can you please clarify? for `armhf` it seems that there's only `client`, while `server` is only available for other archs. Are you saying that, for `armhf`, the `client` should not be installed as part of the current slice?

I apologise for confusion. Yes, we build client for the armhf. 
I was wondering if we can do something like:

```
slices:
  # The "core" slice provides a minimal, yet functional JRE8.
  core:
    essential:
      - libc6_libs
      - libgcc-s1_libs
      - libstdc++6_libs
      - zlib1g_libs
      - openjdk-8-jre-headless_client_vm
      - openjdk-8-jre-headless_server_vm

... 
```
and move the client and server vm contents into separate slices.

_Originally posted by @vpa1977 in https://github.com/canonical/chisel-releases/issues/150#issuecomment-1964936357_
