### ISSUE TITLE
Chiseled `ca-certificates` is incompatible with OpenSSL

### ISSUE THREAD

**Issue by weiiwang01** [canonical/chisel-releases#257]
The chiseled version of `ca-certificates`, `ca-certificates_data`, retains only the single file, the CA certificate bundle at `/etc/ssl/certs/ca-certificates.crt`. However, this file is not default loaded by OpenSSL and applications that use OpenSSL, such as Python.

OpenSSL typically [reads CA certificates from two default system locations](https://www.openssl.org/docs/manmaster/man3/SSL_CTX_load_verify_locations.html):

1. A single file, which in Ubuntu is located at `/usr/lib/ssl/cert.pem`. This location can be overridden by setting the `SSL_CERT_FILE` environment variable.
2. A directory, located in Ubuntu at `/usr/lib/ssl/certs/`, which contains CA certificates named using the format `<hash>.<idx>` (e.g., `9d66eef0.0`, `9d66eef0.1`).

The file `/usr/lib/ssl/certs/ca-certificates.crt` kept by the chiseled `ca-certificates_data` does not correspond to these locations. As a result, applications using OpenSSL, including Python’s standard libraries, encounter SSL verification failures.

There are two potential solutions to this issue. One option is to create a symbolic link from `/usr/lib/ssl/cert.pem` pointed to `/etc/ssl/certs/ca-certificates.crt`. Alternatively, the entire content of the `/usr/lib/ssl/certs/` directory could be kept, rather than just the `ca-certificates.crt` file.

Below is an example rockcraft file to demonstrate the issue:

```yaml
name: test
description: test
summary: test
version: 1.1.1
base: ubuntu@20.04
platforms:
  amd64:
license: Apache-2.0
parts:
  ca-certificates:
    plugin: nil
    stage-packages:
      - ca-certificates_data
  openssl:
    plugin: nil
    stage-packages:
      - openssl
```

The following command can be used to observe the certificate verification failure:

```bash
openssl s_client -connect example.com:443 -servername example.com -showcerts
# ...
#     Verify return code: 20 (unable to get local issuer certificate)
# ...
```
