### ISSUE TITLE
`libncursesw6` slice: fix copyright

### ISSUE THREAD

**Issue by ahouben** [canonical/chisel-releases#413]
[libncursesw6.yaml](https://github.com/canonical/chisel-releases/blob/ubuntu-22.04/slices/libncursesw6.yaml) seems to be missing its copyright slice:
```
package: libncursesw6

slices:
  libs:
    essential:
      - libc6_libs
      - libtinfo6_libs
    contents:
      /lib/*-linux-*/libncursesw.so.6*:
      /usr/lib/*-linux-*/libformw.so.6*:
      /usr/lib/*-linux-*/libmenuw.so.6*:
      /usr/lib/*-linux-*/libpanelw.so.6*:
```
...should probably read...
```
package: libncursesw6

essential:
  - libncursesw6_copyright

slices:
  libs:
    essential:
      - libc6_libs
      - libtinfo6_libs
    contents:
      /lib/*-linux-*/libncursesw.so.6*:
      /usr/lib/*-linux-*/libformw.so.6*:
      /usr/lib/*-linux-*/libmenuw.so.6*:
      /usr/lib/*-linux-*/libpanelw.so.6*:
  copyright:
    essential:
      - libtinfo6_copyright
    contents:
      /usr/share/doc/libncursesw6:
```

See also [https://packages.ubuntu.com/jammy/libncursesw6](https://packages.ubuntu.com/jammy/libncursesw6).
