### ISSUE TITLE
Add `socat` slice

### ISSUE THREAD

**Issue by polarathene** [canonical/chisel-releases#533]
I don't personally need `socat`, but I noticed it was the only slice missing when [I tried porting the `testssl` image (built upon openSUSE Leap)](https://github.com/testssl/testssl.sh/pull/2744#issuecomment-2823107545) to an image built via `chisel` instead.

I did find an old PR at one point contributed a `socat` slice for another package, but then [later dropped it](https://github.com/canonical/chisel-releases/pull/258/commits/1040ce8a986ae6d0e9f44e14b56eff70f4b6e480#diff-e5d3f94a7692fa1a4bbbdcc71ad9f60a2c51c4971e60e3bc17c3b37bf5a270a4). Here's the contents from that link if helpful:

```yaml
package: socat

essential:
  - socat_copyright

slices:
  bins:
    essential:
      - libc6_libs
      - libssl3t64_libs
      - libwrap0_libs
    contents:
      /usr/bin/filan:
      /usr/bin/procan:
      /usr/bin/socat:
      /usr/bin/socat-broker.sh:
      /usr/bin/socat-chain.sh:
      /usr/bin/socat-mux.sh:
      /usr/bin/socat1:

  copyright:
    contents:
      /usr/share/doc/socat/copyright:	
```

Just creating this issue for reference should there be any interest for the slice since most of the work is presumably done above? 🤷‍♂
