### ISSUE TITLE
Add `adduser` slice

### ISSUE THREAD

**Issue by polarathene** [canonical/chisel-releases#549]
**EDIT:** Looks like this will be resolved by: https://github.com/canonical/chisel-releases/pull/305

For reference, the [`busybox` slice](https://github.com/canonical/chisel-releases/blob/fb99e66e3127c73b40e4269f475d292e119414e2/slices/busybox.yaml#L10-L11) should technically also be able to provide `adduser`. Alpine symlinks `/usr/sbin/adduser` to `/bin/busybox` for example.

---

Similar to https://github.com/canonical/chisel-releases/issues/533 this slice had been contributed [initially as part of the PR for another slice but was later removed](https://github.com/canonical/chisel-releases/pull/258/commits/30b159ff9e0dee7835c22752702ade0ec2e38c65#diff-efc87c33b2984ca974559648115b696cce6673d9447ece19fc344a2df8c52e56).

```yaml
package: adduser

essential:
  - adduser_copyright

slices:
  bins:
    essential:
      - adduser_config
      - adduser_modules
      - passwd_bins
    contents:
      /usr/sbin/addgroup:
      /usr/sbin/adduser:
      /usr/sbin/delgroup:
      /usr/sbin/deluser:

  modules:
    contents:
      /usr/share/perl5/Debian/AdduserCommon.pm:
      /usr/share/perl5/Debian/AdduserLogging.pm:
      /usr/share/perl5/Debian/AdduserRetvalues.pm:

  config:
    contents:
      /etc/adduser.conf:
      /etc/deluser.conf:

  copyright:
    contents:
      /usr/share/doc/adduser/copyright:
```
