### ISSUE TITLE
Add `cron` slice

### ISSUE THREAD

**Issue by polarathene** [canonical/chisel-releases#550]
Similar to https://github.com/canonical/chisel-releases/issues/533 this slice had been contributed [initially as part of the PR for another slice but was later removed](https://github.com/canonical/chisel-releases/pull/258/commits/30b159ff9e0dee7835c22752702ade0ec2e38c65#diff-c616c5da460e2242835a03b0668f8f578544aa35abae8b6763b0ad0594c07b2c).

The contribution involved two slices related to `cron`:

**`cron-daemon-common.yaml`:**

```yaml
package: cron-daemon-common

essential:
  - cron-daemon-common_copyright

slices:
  config:
    essential:
      - adduser_bins
    contents:
      /etc/cron.d/.placeholder:
      /etc/cron.daily/.placeholder:
      /etc/cron.hourly/.placeholder:
      /etc/cron.monthly/.placeholder:
      /etc/cron.weekly/.placeholder:
      /etc/cron.yearly/.placeholder:
      /etc/crontab:
      /usr/lib/sysusers.d/cron-daemon-common.conf:
      /usr/lib/tmpfiles.d/cron-daemon-common.conf:

  copyright:
    contents:
      /usr/share/doc/cron-daemon-common/copyright:
```

**`cron`:**

```yaml
package: cron

essential:
  - cron_copyright

slices:
  bins:
    essential:
      - cron-daemon-common_config
      - cron_config
      - init-system-helpers_bins
      - libc6_libs
      - libpam-runtime_bins
      - libpam0g_libs
      - libselinux1_libs
      - sensible-utils_bins
    contents:
      /usr/bin/crontab:
      /usr/sbin/cron:

  config:
    contents:
      /etc/default/cron:
      /etc/init.d/cron:
      /etc/pam.d/cron:
      /etc/supercat/spcrc-crontab:
      /etc/supercat/spcrc-crontab-light:

  copyright:
    contents:
      /usr/share/doc/cron/copyright:
```
