### ISSUE TITLE
Add `logrotate` slice

### ISSUE THREAD

**Issue by polarathene** [canonical/chisel-releases#551]
Similar to https://github.com/canonical/chisel-releases/issues/533 this slice had been contributed [initially as part of the PR for another slice but was later removed](https://github.com/canonical/chisel-releases/pull/258/commits/30b159ff9e0dee7835c22752702ade0ec2e38c65#diff-b04d93f08ee55832ae7b2c4a258fe261723fb3b71a911cabca87f15b6e3714dc).

The contribution involved two slices related to `logrotate`:

**`logrotate.yaml`:**

```yaml
package: logrotate

essential:
  - logrotate_copyright

slices:
  bins:
    essential:
      - cron_bins
      - libacl1_libs
      - libc6_libs
      - libpopt0_libs
      - libselinux1_libs
      - logrotate_config
    contents:
      /usr/sbin/logrotate:

  config:
    contents:
      /etc/cron.daily/logrotate:
      /etc/logrotate.conf:
      /etc/logrotate.d/btmp:
      /etc/logrotate.d/wtmp:

  copyright:
    contents:
      /usr/share/doc/logrotate/copyright:
```

**`libpopt0.yaml`:**

```yaml
package: libpopt0

essential:
  - libpopt0_copyright

slices:
  libs:
    essential:
      - libc6_libs
    contents:
      /usr/lib/*-linux-*/libpopt.so.0*:

  copyright:
    contents:
      /usr/share/doc/libpopt0/copyright:
```

These depend upon the [`cron` slices](https://github.com/canonical/chisel-releases/issues/550).
