### ISSUE TITLE
Add `drill` / `ldnsutils`

### ISSUE THREAD

**Issue by polarathene** [canonical/chisel-releases#554]
`drill` has much less dependencies linked than `dig` (`bind9-dnsutils_bins`_) or `kdig` (_no `knot-dnsutils` slice_). In an image approx 50MB in size already (_porting attempt to `chisel` [here](https://github.com/testssl/testssl.sh/issues/2422#issuecomment-2841822406)_) with common shared dependencies, adding `dig` increased image weight by 47MB, while this custom slice for `drill` only adds 480KB (3 files).

I have not written a custom slice before this, and the below example that I pieced together seems accurate for `drill`, but from what I understand the slices must be aligned to a package name which would be a bit misleading as I've excluded anything unrelated to `drill`.

Sharing here in case it helps someone else :)

---

**`ldnsutils.yaml`:**

```yaml
package: ldnsutils

essential:
  - ldnsutils_copyright

slices:
  bins:
    essential:
      - libc6_libs
      - libldns3t64_libs
    contents:
      /usr/bin/drill:

  copyright:
    contents:
      /usr/share/doc/ldnsutils/copyright:
```

**`libldns3t64.yaml`:**

```yaml
package: libldns3t64

essential:
  - libldns3t64_copyright

slices:
  libs:
    essential:
      - libc6_libs
      - libidn2-0_libs
      - libssl3t64_libs
    contents:
      /usr/lib/*-linux-*/libldns.so.*:

  copyright:
    contents:
      /usr/share/doc/libldns3t64/copyright:
```

**Comment by cjdcordeiro** [comment]
Well done on your first slice definitions @polarathene ;)

They actually look quite reasonable, so I'd encourage your to open a PR for them :)

As for the `drill` <pkg_slice> naming, since that are many other bins in that package, I'd actually recommend creating a slice just for `drill`

```yaml
slices:
  drill:
    essential:
      - libc6_libs
      - libldns3t64_libs
    contents:
      /usr/bin/drill:
```

I'll keep this issue open in case you want to raise a PR for it ;)
