### ISSUE TITLE
refactor the openssl slices

### ISSUE THREAD

**Issue by cjdcordeiro** [canonical/chisel-releases#60]
> I've edited the file to place `/usr/lib/ssl/cert.pem` in a `data` slice instead, since that's a symlink to a data file from ca-certificates. Hope that's ok

I think in this case, we will need a to modify the slice to something like this:

```yaml
package: openssl

slices:
  libs:
    essential:
      - libc6_libs
      - libc6_config
      - libssl3_libs
      - openssl_config
      - openssl_data
  bins:
    essential:
      - openssl_libs
    contents:
      /usr/bin/c_rehash:
      /usr/bin/openssl:

  config:
    contents:
      /etc/ssl/private/:
      /etc/ssl/openssl.cnf:
      /usr/lib/ssl/certs:
      /usr/lib/ssl/openssl.cnf:
      /usr/lib/ssl/private:

  data:
    contents:
      /usr/lib/ssl/cert.pem:
```

... so that if the applications only need the libraries and data, they can include libraries and data without the OpenSSL tools.

_Originally posted by @liushuyu in https://github.com/canonical/chisel-releases/issues/40#issuecomment-1708771341_
